import type { Asset } from "@/data/assets.generated";
import { work, type WorkItem } from "@/data/work";

export type ShotGroup = {
  item: WorkItem;
  shots: Asset[];
};

/**
 * The feed, filed under the product each frame came from.
 *
 * `/shots` holds fourteen App Store screenshots and nothing else, and they are
 * uniform: same device, same orientation, same 1284x2778. A reader looking at
 * a wall of fourteen phone screens has exactly one question — which app is
 * this — and the filename that answers it is not on the page. Grouping is the
 * answer, and it is derived rather than declared: the manifest is generated by
 * `scripts/manifest.mjs`, so a hand-kept list of which file belongs to which
 * product would go stale the first time somebody drops a file in.
 *
 * The join is the filename's prefix against `data/work.ts`'s slug, which is
 * also the convention the files were named under. Order is the record's: the
 * groups come out in the order the work is listed, and the frames inside a
 * group stay in the order the manifest found them, which is the order they
 * appear on the listing.
 *
 * Anything that matches no slug comes back as `unfiled` rather than being
 * dropped or guessed at. A frame nobody can place is a fact about the
 * repository, and `lib/shots.test.ts` asserts the committed manifest has none.
 */
export function groupShots(shots: readonly Asset[]): {
  groups: ShotGroup[];
  unfiled: Asset[];
} {
  const taken = new Set<string>();

  const groups = work
    .map((item) => {
      const prefix = `/shots/${item.slug}-`;
      const owned = shots.filter((shot) => shot.src.startsWith(prefix));
      for (const shot of owned) taken.add(shot.src);
      return { item, shots: owned };
    })
    .filter((group) => group.shots.length > 0);

  return { groups, unfiled: shots.filter((shot) => !taken.has(shot.src)) };
}
