import type { Asset } from "@/data/assets.generated";
import { work, type WorkItem } from "@/data/work";

export type ShotGroup = {
  item: WorkItem;
  shots: Asset[];
};

/**
 * The feed, filed under the product each frame came from.
 *
 * `/shots` holds the products' own imagery — App Store screenshots plus the
 * artwork sheets the owner supplied — filed under the product each frame came
 * from. The phone screens are uniform: same device, same orientation, same
 * 1284x2778 (and the owner-supplied 2026-09-17 screens are 9:19.5 too). A
 * reader looking at
 * a wall of fourteen phone screens has exactly one question — which app is
 * this — and the filename that answers it is not on the page. Grouping is the
 * answer, and it is derived rather than declared: the manifest is generated by
 * `scripts/manifest.mjs`, so a hand-kept list of which file belongs to which
 * product would go stale the first time somebody drops a file in.
 *
 * The join is the filename's prefix against `data/work.ts`'s slug, which is
 * also the convention the files were named under. Order is the record's: the
 * groups come out in the order the work is listed, and the frames inside a
 * group stay in the order the manifest found them, which is the order they
 * appear on the listing.
 *
 * Anything that matches no slug comes back as `unfiled` rather than being
 * dropped or guessed at. A frame nobody can place is a fact about the
 * repository, and `lib/shots.test.ts` asserts the committed manifest has none.
 */
export function groupShots(shots: readonly Asset[]): {
  groups: ShotGroup[];
  unfiled: Asset[];
} {
  const taken = new Set<string>();

  const groups = work
    .map((item) => {
      const prefix = `/shots/${item.slug}-`;
      const owned = shots.filter((shot) => shot.src.startsWith(prefix));
      for (const shot of owned) taken.add(shot.src);
      return { item, shots: owned };
    })
    .filter((group) => group.shots.length > 0);

  return { groups, unfiled: shots.filter((shot) => !taken.has(shot.src)) };
}

/**
 * Where a product's case rail ends, by the last screen it shows.
 *
 * The Endgame rail ends at the Settings screen (08). Everything past it is
 * contact-sheet cuts the owner says are not Endgame screens. A product with
 * no entry shows its whole feed group on its rail. The slice is inclusive of
 * the marker; a missing marker falls back to the whole group rather than an
 * empty rail.
 */
export const RAIL_END: Record<string, string> = {
  "endgame-ai": "/shots/endgame-ai-08.jpg",
};

/**
 * The feed minus what the cases already show, so no screen appears twice.
 *
 * Case rails scroll each product's own feed screens, so the Shots strip and
 * the /shots archive show only what the rails do not: everything past the
 * rail marker. A group the rail covers completely (ChessEver) drops out
 * rather than printing an empty rail. XD keeps no feed at all — its screens
 * live in its case — so nothing of XD's ever reaches the strip.
 */
export function stripShots(groups: ShotGroup[]): ShotGroup[] {
  return groups.flatMap((group) => {
    const end = RAIL_END[group.item.slug];
    /* No marker means the rail scrolls the whole group — nothing left over. */
    if (!end) return [];
    const at = group.shots.findIndex((shot) => shot.src === end);
    const extras = at === -1 ? group.shots : group.shots.slice(at + 1);
    return extras.length > 0 ? [{ ...group, shots: extras }] : [];
  });
}
