// Generated by scripts/manifest.mjs — do not edit by hand.
// Run `pnpm manifest` after dropping files into public/shots or public/work/<slug>.

export type Asset = {
  src: string;
  title: string;
  date: string | null;
  width: number;
  height: number;
};

export const feedAssets: Asset[] = [
  {
    "src": "/shots/chessever-01.jpg",
    "title": "Chessever 01",
    "date": null,
    "height": 1792,
    "width": 886
  },
  {
    "src": "/shots/chessever-02.jpg",
    "title": "Chessever 02",
    "date": null,
    "height": 1792,
    "width": 886
  },
  {
    "src": "/shots/chessever-03.jpg",
    "title": "Chessever 03",
    "date": null,
    "height": 1792,
    "width": 886
  },
  {
    "src": "/shots/chessever-04.jpg",
    "title": "Chessever 04",
    "date": null,
    "height": 1792,
    "width": 886
  },
  {
    "src": "/shots/chessever-05.jpg",
    "title": "Chessever 05",
    "date": null,
    "height": 1792,
    "width": 886
  },
  {
    "src": "/shots/chessever-06.jpg",
    "title": "Chessever 06",
    "date": null,
    "height": 1792,
    "width": 886
  },
  {
    "src": "/shots/chessever-07.jpg",
    "title": "Chessever 07",
    "date": null,
    "height": 1792,
    "width": 886
  },
  {
    "src": "/shots/chessever-08.jpg",
    "title": "Chessever 08",
    "date": null,
    "height": 1792,
    "width": 886
  },
  {
    "src": "/shots/endgame-ai-01.jpg",
    "title": "Endgame ai 01",
    "date": null,
    "height": 2803,
    "width": 1290
  },
  {
    "src": "/shots/endgame-ai-02.jpg",
    "title": "Endgame ai 02",
    "date": null,
    "height": 2803,
    "width": 1290
  },
  {
    "src": "/shots/endgame-ai-03.jpg",
    "title": "Endgame ai 03",
    "date": null,
    "height": 2803,
    "width": 1290
  },
  {
    "src": "/shots/endgame-ai-04.jpg",
    "title": "Endgame ai 04",
    "date": null,
    "height": 2803,
    "width": 1290
  },
  {
    "src": "/shots/endgame-ai-05.jpg",
    "title": "Endgame ai 05",
    "date": null,
    "height": 2803,
    "width": 1290
  },
  {
    "src": "/shots/endgame-ai-06.jpg",
    "title": "Endgame ai 06",
    "date": null,
    "height": 2803,
    "width": 1290
  },
  {
    "src": "/shots/endgame-ai-07.jpg",
    "title": "Endgame ai 07",
    "date": null,
    "height": 2803,
    "width": 1290
  },
  {
    "src": "/shots/endgame-ai-08.jpg",
    "title": "Endgame ai 08",
    "date": null,
    "height": 2803,
    "width": 1290
  },
  {
    "src": "/shots/endgame-ai-09.png",
    "title": "Endgame ai 09",
    "date": null,
    "width": 786,
    "height": 1704
  },
  {
    "src": "/shots/endgame-ai-10.png",
    "title": "Endgame ai 10",
    "date": null,
    "width": 786,
    "height": 1704
  },
  {
    "src": "/shots/endgame-ai-11.png",
    "title": "Endgame ai 11",
    "date": null,
    "width": 1572,
    "height": 3408
  },
  {
    "src": "/shots/endgame-ai-12.png",
    "title": "Endgame ai 12",
    "date": null,
    "width": 786,
    "height": 1704
  },
  {
    "src": "/shots/endgame-ai-13.png",
    "title": "Endgame ai 13",
    "date": null,
    "width": 1572,
    "height": 3408
  },
  {
    "src": "/shots/endgame-ai-14.png",
    "title": "Endgame ai 14",
    "date": null,
    "width": 1572,
    "height": 3408
  },
  {
    "src": "/shots/endgame-ai-15.png",
    "title": "Endgame ai 15",
    "date": null,
    "width": 786,
    "height": 1704
  },
  {
    "src": "/shots/endgame-ai-16.png",
    "title": "Endgame ai 16",
    "date": null,
    "width": 786,
    "height": 1704
  },
  {
    "src": "/shots/endgame-ai-18.png",
    "title": "Endgame ai 18",
    "date": null,
    "width": 3450,
    "height": 1120
  },
  {
    "src": "/shots/endgame-ai-19.png",
    "title": "Endgame ai 19",
    "date": null,
    "width": 3456,
    "height": 1032
  },
  {
    "src": "/shots/endgame-ai-20.png",
    "title": "Endgame ai 20",
    "date": null,
    "width": 2920,
    "height": 2448
  },
  {
    "src": "/shots/endgame-ai-21.png",
    "title": "Endgame ai 21",
    "date": null,
    "width": 854,
    "height": 1864
  },
  {
    "src": "/shots/endgame-ai-22.png",
    "title": "Endgame ai 22",
    "date": null,
    "width": 786,
    "height": 1639
  },
  {
    "src": "/shots/endgame-ai-23.png",
    "title": "Endgame ai 23",
    "date": null,
    "width": 786,
    "height": 1866
  },
  {
    "src": "/shots/endgame-ai-24.png",
    "title": "Endgame ai 24",
    "date": null,
    "width": 720,
    "height": 1582
  },
  {
    "src": "/shots/endgame-ai-25.png",
    "title": "Endgame ai 25",
    "date": null,
    "width": 720,
    "height": 1582
  },
  {
    "src": "/shots/endgame-ai-26.png",
    "title": "Endgame ai 26",
    "date": null,
    "width": 720,
    "height": 1470
  },
  {
    "src": "/shots/endgame-ai-27.png",
    "title": "Endgame ai 27",
    "date": null,
    "width": 720,
    "height": 1582
  },
  {
    "src": "/shots/endgame-ai-28.png",
    "title": "Endgame ai 28",
    "date": null,
    "width": 720,
    "height": 1440
  },
  {
    "src": "/shots/endgame-ai-29.png",
    "title": "Endgame ai 29",
    "date": null,
    "width": 720,
    "height": 1440
  },
  {
    "src": "/shots/endgame-ai-30.png",
    "title": "Endgame ai 30",
    "date": null,
    "width": 720,
    "height": 1596
  }
];

export const workAssets: Record<string, Asset[]> = {};
