// Generated by scripts/manifest.mjs — do not edit by hand.
// Run `pnpm manifest` after dropping files into public/shots or public/work/<slug>.

export type Asset = {
  src: string;
  title: string;
  date: string | null;
  width: number;
  height: number;
};

export const feedAssets: Asset[] = [
  {
    "src": "/shots/chessever-01.jpg",
    "title": "Chessever 01",
    "date": null,
    "height": 2778,
    "width": 1284
  },
  {
    "src": "/shots/chessever-02.jpg",
    "title": "Chessever 02",
    "date": null,
    "height": 2778,
    "width": 1284
  },
  {
    "src": "/shots/chessever-03.jpg",
    "title": "Chessever 03",
    "date": null,
    "height": 2778,
    "width": 1284
  },
  {
    "src": "/shots/chessever-04.jpg",
    "title": "Chessever 04",
    "date": null,
    "height": 2778,
    "width": 1284
  },
  {
    "src": "/shots/chessever-05.jpg",
    "title": "Chessever 05",
    "date": null,
    "height": 2778,
    "width": 1284
  },
  {
    "src": "/shots/chessever-06.jpg",
    "title": "Chessever 06",
    "date": null,
    "height": 2778,
    "width": 1284
  },
  {
    "src": "/shots/endgame-ai-01.jpg",
    "title": "Endgame ai 01",
    "date": null,
    "height": 2803,
    "width": 1290
  },
  {
    "src": "/shots/endgame-ai-02.jpg",
    "title": "Endgame ai 02",
    "date": null,
    "height": 2803,
    "width": 1290
  },
  {
    "src": "/shots/endgame-ai-03.jpg",
    "title": "Endgame ai 03",
    "date": null,
    "height": 2803,
    "width": 1290
  },
  {
    "src": "/shots/endgame-ai-04.jpg",
    "title": "Endgame ai 04",
    "date": null,
    "height": 2803,
    "width": 1290
  },
  {
    "src": "/shots/endgame-ai-05.jpg",
    "title": "Endgame ai 05",
    "date": null,
    "height": 2803,
    "width": 1290
  },
  {
    "src": "/shots/endgame-ai-06.jpg",
    "title": "Endgame ai 06",
    "date": null,
    "height": 2803,
    "width": 1290
  },
  {
    "src": "/shots/endgame-ai-07.jpg",
    "title": "Endgame ai 07",
    "date": null,
    "height": 2803,
    "width": 1290
  },
  {
    "src": "/shots/endgame-ai-08.jpg",
    "title": "Endgame ai 08",
    "date": null,
    "height": 2803,
    "width": 1290
  },
  {
    "src": "/shots/endgame-ai-09.jpg",
    "title": "Endgame ai 09",
    "date": null,
    "height": 429,
    "width": 210
  },
  {
    "src": "/shots/endgame-ai-10.jpg",
    "title": "Endgame ai 10",
    "date": null,
    "height": 426,
    "width": 210
  },
  {
    "src": "/shots/endgame-ai-11.jpg",
    "title": "Endgame ai 11",
    "date": null,
    "height": 426,
    "width": 210
  },
  {
    "src": "/shots/endgame-ai-12.jpg",
    "title": "Endgame ai 12",
    "date": null,
    "height": 454,
    "width": 210
  },
  {
    "src": "/shots/endgame-ai-13.jpg",
    "title": "Endgame ai 13",
    "date": null,
    "height": 454,
    "width": 210
  },
  {
    "src": "/shots/endgame-ai-14.jpg",
    "title": "Endgame ai 14",
    "date": null,
    "height": 454,
    "width": 210
  },
  {
    "src": "/shots/endgame-ai-15.jpg",
    "title": "Endgame ai 15",
    "date": null,
    "height": 454,
    "width": 210
  },
  {
    "src": "/shots/endgame-ai-16.jpg",
    "title": "Endgame ai 16",
    "date": null,
    "height": 454,
    "width": 210
  }
];

export const workAssets: Record<string, Asset[]> = {};
